services:
  - type: web
    name: minimal-oidc-sharedpass
    runtime: docker
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: ISSUER
        sync: false
      - key: OIDC_CLIENT_ID
        sync: false
      - key: OIDC_CLIENT_SECRET
        sync: false
      - key: OIDC_REDIRECT_URI
        sync: false
      - key: EMAIL_DOMAIN
        sync: false
      - key: SHARED_PASSWORD
        sync: false
      - key: ALLOW_ANY_PREFIX
        value: "true"
      - key: ALLOWED_PREFIXES
        value: ""
      - key: TOKEN_TTL_SECONDS
        value: "300"
      - key: DATA_DIR
        value: "/app/data"
      - key: OIDC_PRIVATE_KEY_B64
        sync: false
      - key: OIDC_KEY_ID
        value: "render-sso-key-1"
