services:
  - type: web
    name: render-sso-google-oidc
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: ALLOWED_EMAIL_DOMAIN
        sync: false
